### ISSUE TITLE
Player defined joruney

### ISSUE THREAD

**Issue by rc1035** [SEPR-EEP/taxe-game#11]
1) A player should not be able to specify a path of a new journey on the map until the train is no longer moving, i.e. its current journey is complete.

2) A player should not be able to end their turn if the path they have specified ends at a junction, this is not a valid routing.

**Comment by AlfioEmanueleFresta** [comment]
I am not very sure about 1). I think the player should be able to re-route a train in transit - otherwise once all of your trains are already moving there is not much you can do. Also, if you re-route, you slow down as you can start the journey from the last visited station (so you loose the time of the distance travelled on the current edge). What do you think?

**Comment by rc1035** [comment]
Okay, that sounds like a good idea. Closing as no. 2) is fixed.
