### ISSUE TITLE
Ghost train

### ISSUE THREAD

**Issue by rc1035** [SEPR-EEP/taxe-game#12]
In some instances the opposing train does not show. I have tried commenting out changes I have made yet the opposing train still sometimes does not display. If you proceed for a number of turns it sometimes reappears.

**Comment by AlfioEmanueleFresta** [comment]
Does the opponent's train not show in both client at the same time? Or the other player is able to view both trains?

**Comment by AlfioEmanueleFresta** [comment]
This just happened to me. I have the impression there might be some problem with calculating the current position of the player - leading to drawing the train out of the visible screen. 
![image](https://cloud.githubusercontent.com/assets/621062/5793383/6c399128-9f39-11e4-8f12-c9846e405ccf.png)

**Comment by rc1035** [comment]
When the bug occured was the starting station for both players the same?

It took 8 attempts for the error to occur for me and it happened when both trains started at Sofia.

**Comment by AlfioEmanueleFresta** [comment]
When two trains are stopped at the same station they are drawn one over the other. My trains are always higher priority and drawn on top, so when this happens, both players see one green train. I was thinking of maybe, when drawing the opponent's train, having it with a (2px, 2px) offset so that it can be seen behind the green train.

**Comment by AlfioEmanueleFresta** [comment]
Fixed in 8e08d2c3e6b900609a0ea87ff39ebee1dece6487.
